// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversitySchedule.Infrastructure.Persistence;

#nullable disable

namespace UniversitySchedule.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830102807_AddCatalogAndScheduleCache")]
    partial class AddCatalogAndScheduleCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversitySchedule.Domain.Catalog.ReferenceCatalogDocument", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("SourceGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_generated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_reference_catalog_content_hash");

                    b.ToTable("reference_catalog_documents", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.Catalog.ReferenceCatalogImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer")
                        .HasColumnName("group_count");

                    b.Property<int>("ProgramCount")
                        .HasColumnType("integer")
                        .HasColumnName("program_count");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TeacherCount")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_count");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_reference_catalog_import_started_at");

                    b.ToTable("reference_catalog_import_logs", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.Identity.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_installations_last_seen_at_utc");

                    b.ToTable("installations", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.PersonalDataMutationReceipt", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<Guid>("MutationId")
                        .HasColumnType("uuid")
                        .HasColumnName("mutation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityKind")
                        .HasColumnType("integer")
                        .HasColumnName("entity_kind");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("InstallationId", "MutationId");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_mutation_receipts_processed_at_utc");

                    b.ToTable("personal_data_mutation_receipts", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.SyncedAssignment", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClientUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_updated_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid>("LastMutationId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_mutation_id");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("ServerUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_updated_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("text");

                    b.HasKey("InstallationId", "Id");

                    b.HasIndex("InstallationId", "ServerUpdatedAtUtc")
                        .HasDatabaseName("ix_assignments_installation_server_updated");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.SyncedNote", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClientUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_updated_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<Guid>("LastMutationId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_mutation_id");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("ServerUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_updated_at_utc");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("InstallationId", "Id");

                    b.HasIndex("InstallationId", "ServerUpdatedAtUtc")
                        .HasDatabaseName("ix_notes_installation_server_updated");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.Scheduling.ScheduleSourceDocument", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.HasKey("Key");

                    b.HasIndex("FetchedAtUtc")
                        .HasDatabaseName("ix_schedule_source_documents_fetched_at");

                    b.ToTable("schedule_source_documents", (string)null);
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.PersonalDataMutationReceipt", b =>
                {
                    b.HasOne("UniversitySchedule.Domain.Identity.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.SyncedAssignment", b =>
                {
                    b.HasOne("UniversitySchedule.Domain.Identity.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversitySchedule.Domain.PersonalData.SyncedNote", b =>
                {
                    b.HasOne("UniversitySchedule.Domain.Identity.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
